import { MigrationInterface, QueryRunner } from 'typeorm';

// `CampaignOrganizer` and `CampaignOrganizerFollow` were promoted to
// extend `AbstractEntity`, which adds `updated_at` and `deleted_at`
// columns. The original `CreateCampaignOrganizers` migration predates
// that change, so the live DB is missing those columns and any SELECT
// generated by TypeORM throws
// `Unknown column 'CampaignOrganizer.updated_at'`.
//
// Strictly additive — no drops, no renames. Existing rows backfill
// `updated_at` to `created_at` so the on-update trigger has sane
// initial values.
export class AddAbstractEntityColsToCampaignOrganizers1778000000001
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`campaign_organizers\`
         ADD COLUMN \`updated_at\` TIMESTAMP(6)
           NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
           ON UPDATE CURRENT_TIMESTAMP(6),
         ADD COLUMN \`deleted_at\` TIMESTAMP(6) NULL DEFAULT NULL`,
    );
    await queryRunner.query(
      `UPDATE \`campaign_organizers\`
         SET \`updated_at\` = \`created_at\`
         WHERE \`updated_at\` IS NULL OR \`updated_at\` < \`created_at\``,
    );

    await queryRunner.query(
      `ALTER TABLE \`campaign_organizer_follows\`
         ADD COLUMN \`updated_at\` TIMESTAMP(6)
           NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
           ON UPDATE CURRENT_TIMESTAMP(6),
         ADD COLUMN \`deleted_at\` TIMESTAMP(6) NULL DEFAULT NULL`,
    );
    await queryRunner.query(
      `UPDATE \`campaign_organizer_follows\`
         SET \`updated_at\` = \`created_at\`
         WHERE \`updated_at\` IS NULL OR \`updated_at\` < \`created_at\``,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`campaign_organizer_follows\`
         DROP COLUMN \`updated_at\`,
         DROP COLUMN \`deleted_at\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`campaign_organizers\`
         DROP COLUMN \`updated_at\`,
         DROP COLUMN \`deleted_at\``,
    );
  }
}
